FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV PORT=5678
ENV N8N_SECURE_COOKIE=false

COPY workflows /home/node/workflows
COPY start.sh /home/node/start.sh

USER root
RUN chmod +x /home/node/start.sh
USER node

EXPOSE 5678

CMD ["/home/node/start.sh"]